import = ["~/.config/alacritty/tokyonight.toml"]

[env]
TERM="xterm-256color"

[window]
padding = { x = 3, y = 3 }
startup_mode="Fullscreen"
decorations="None"

[font]
normal={family = "FantasqueSansM Nerd Font Mono", style = "Regular"}
bold={family = "FantasqueSansM Nerd Font Mono", style = "Bold"}
italic={family = "FantasqueSansM Nerd Font Mono", style = "Italic"}
bold_italic={family = "FantasqueSansM Nerd Font Mono", style = "Bold Italic"}
size = 14.0
