#!/usr/bin/env bash

# Script to switch to or create a new tmux session
# Credit to ThePrimeagen

# Check if a directory was passed as an argument
if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Find directories in ~/Code and append /tmp, then select one using fzf
    items=$(find ~/Code -maxdepth 2 -mindepth 1 -type d)
    items+=$(echo -e "\n/tmp")
    selected=$(echo "$items" | fzf)
fi

# Exit if no directory was selected
if [[ -z $selected ]]; then
    exit 1
fi

# Replace periods with underscores in the selected directory name
dirname=$(basename "$selected" | tr '.' '_')

# Try to switch to an existing tmux session
if tmux switch-client -t="$dirname"; then
    exit 0
fi

# Create a new tmux session if switching failed
if ! tmux new-session -c "$selected" -d -s "$dirname"; then
    tmux new -c "$selected" -A -s "$dirname"
fi
